language: python
python:
  - 3.4
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r requirements.txt
script:
  - py.test --ds=project.settings --cov apps
after_success:
  - coveralls
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: Z8Zo+o2zuSI8Hi/UJgpGUu6J0ozuGelxH6VP+1E187r2NHR+qiu6s/4tTzfO+hMrjmqRsRZlEaxJkZt/04BubMSmDST01TMSRyAy7hOjcSbZgwxSyrnBuMppWctxjL+sqj2od+bzSEh1Qa+UTqxIRy2bZJDPuJEwQftSg2A4syE=
  app:
    master: project
    dev: project-staging
  run:
  - python manage.py migrate --noinput
